- name: Install Apache Web Server with PHP
  hosts: all
  become: yes

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Ensure apache2 is installed
      apt:
        name: apache2
        state: present

    - name: Install PHP support
      apt:
        name: libapache2-mod-php
        state: present
